name: C/C++ CI

on:
  push:
    branches: [ main, morelang ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20230501

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: |
          ThirdTube-morelang.3dsx
          ThirdTube-morelang.cia
          ThirdTube-DE.cia
          ThirdTube-DE.smdh
